apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: lkristoffy/my_app:v1
        ports:
        - containerPort: 9999
        env:
        - name: ENVIRONMENT
          value: "production" 

---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80      # Port exposed to external traffic
      targetPort: 9999  # Port inside the container
  type: LoadBalancer 